### PR TITLE
Overscan and aspect ratio core options

### PR DESCRIPTION
**Pull request by Monroe88**
Overscan is controlled by core option now instead of RETRO_ENVIRONMENT_GET_OVERSCAN.

Core reported aspect ratio can now be set to 8:7 PAR (like in higan) or 4:3 DAR.

Also, update geometry when options are changed.

### CODE REVIEW

**Comment by Alcaro** [comment]
> \+ else if(!strcmp(var.value, "disabled"))
> \+ else if(!strcmp(var.value, "4:3"))

No real need for elseif, just use else. If the frontend hands out values other than those two, it's broken, and let's just assume it's not.

> \+ core_bind.penviron(RETRO_ENVIRONMENT_SET_GEOMETRY, &av_info);

@twinaphex, is it safe to call this when not needed?

Other than that, +1

**Comment by Alcaro** [comment]
That's not how it works, you can always read those envs. (I'm not even sure if it's worth success checking them. Probably is, it does no harm.)

You'll need something like
```
if (core_bind.penviron(RETRO_ENVIRONMENT_GET_VARIABLE, &var) && var.value) {
  bool newval = (!strcmp(var.value, "enabled"));
  if (newval != core_bind.overscan)
  {
    core_bind.overscan = newval;
    geometry_update = true;
  }
}
```

**Comment by Monroe88** [comment]
Does this look good to be merged now? I implemented the suggested changes here and in the Snes9x PR as well, and it seems to be working perfectly.

Thank you for the coding tips.

**Comment by Monroe88** [comment]
Closing in favor of the other pull request

**Pull request closed without merging**
